// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  // Firebase configuration from synther-pro-holo project
  static const String _firebaseApiKey = 'AIzaSyCTWZsQTMVeaEsHXrg_pEF_CCzI7sYlZPw';
  static const String _firebaseProjectId = 'synther-pro-holo';
  static const String _firebaseMessagingSenderId = '872646180221';
  static const String _firebaseAuthDomain = 'synther-pro-holo.firebaseapp.com';
  static const String _firebaseStorageBucket = 'synther-pro-holo.firebasestorage.app';
  static const String _firebaseMeasurementId = 'G-0VTPFYY5Q7';
  static const String _firebaseIosBundleId = 'com.example.synther';

  // Platform-specific App IDs
  static const String _firebaseAppIdWeb = '1:872646180221:web:c394d10b5b82696417a014';
  static const String _firebaseAppIdAndroid = '1:872646180221:android:6c4d1ee3c5092d0417a014';
  static const String _firebaseAppIdIos = '1:872646180221:ios:c394d10b5b82696417a014';
  static const String _firebaseAppIdLinux = '1:872646180221:web:c394d10b5b82696417a014';
  // It's also common to have different API keys per platform, but for simplicity here, one main key is used.
  // If platform-specific API keys are needed, define more String.fromEnvironment variables like:
  // static const String _firebaseApiKeyWeb = String.fromEnvironment('FIREBASE_API_KEY_WEB', defaultValue: _firebaseApiKey);

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Replaced UnsupportedError
      case TargetPlatform.iOS:
        return ios; // Replaced UnsupportedError
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux; // Return Linux options
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _firebaseApiKey,
    appId: _firebaseAppIdWeb,
    messagingSenderId: _firebaseMessagingSenderId,
    projectId: _firebaseProjectId,
    authDomain: _firebaseAuthDomain,
    storageBucket: _firebaseStorageBucket,
    measurementId: _firebaseMeasurementId, // Web often uses measurementId
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _firebaseApiKey, // Assuming same API key, or use _firebaseApiKeyAndroid
    appId: _firebaseAppIdAndroid,
    messagingSenderId: _firebaseMessagingSenderId,
    projectId: _firebaseProjectId,
    authDomain: _firebaseAuthDomain, // Added from web, ensure it's correct for Android too
    storageBucket: _firebaseStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _firebaseApiKey, // Assuming same API key, or use _firebaseApiKeyIos
    appId: _firebaseAppIdIos,
    messagingSenderId: _firebaseMessagingSenderId,
    projectId: _firebaseProjectId,
    authDomain: _firebaseAuthDomain, // Added from web
    storageBucket: _firebaseStorageBucket,
    iosBundleId: _firebaseIosBundleId,
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: _firebaseApiKey, // Assuming same API key, or use _firebaseApiKeyLinux
    appId: _firebaseAppIdLinux,
    messagingSenderId: _firebaseMessagingSenderId,
    projectId: _firebaseProjectId,
    authDomain: _firebaseAuthDomain, // Added from web
    storageBucket: _firebaseStorageBucket,
    // measurementId: _firebaseMeasurementId, // Linux might use measurementId if using Analytics
  );
}
